name: enocraft-plugin-v2
version: '${version}'
main: kimit.enocraft.Main
api-version: 1.19
authors: [ Kimit ]
description: Enocraft Plugin V2

commands:
  test:
    description: asdf
    usage: /<command>
    permission: enocraft.test
  newpage:
    description: asdf
    usage: /<command>
    permission: enocraft.newpage
  removepage:
    description: asdf
    usage: /<command>
    permission: enocraft.removepage
  openpage:
    description: asdf
    usage: /<command>
    permission: enocraft.openpage
  receive:
    description: Open player's received item inventory.
    usage: /<command>
    permission: enocraft.receive
  market:
    description: Open market.
    usage: /<command>
    permission: enocraft.market
  sell:
    description: Sell item
    usage: /<command>
    permission: enocraft.market.sell
  getcash:
    description: Sell item
    usage: /<command>
    permission: enocraft.getcash
  setcash:
    description: Sell item
    usage: /<command>
    permission: enocraft.setcash